name: Deploy to Cloud Run

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: ">= 363.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-express-cicd:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-express-cicd:latest

      - name: Deploy
        run: |
          gcloud run deploy node-express-cicd \
          --region us-central1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-express-cicd \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
